In [1]:
import numpy as np

In [5]:
arr = np.arange(1,11)

In [6]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [10]:
arr + 10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [12]:
np.max(arr)

np.int64(10)

In [13]:
np.min(arr)

np.int64(1)

In [14]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])