In [3]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr [1:5]

array([1, 2, 3, 4])

In [7]:
slice_of_arr = arr[0:5]

In [8]:
slice_of_arr [ : ] = 99

In [9]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [10]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [11]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
numbers

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
numbers_array = np.array(numbers)

In [14]:
numbers_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
numbers_array_copy = numbers_array.copy()

In [16]:
numbers_array_copy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
numbers_array_copy [ : ] = 00

In [18]:
numbers_array_copy

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
numbers_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [23]:
x_array = np.array(x)

In [24]:
x_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
x_array.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])